version: '3.9'

services:
  client:
    build:
      context: ./client
      args:
        - REACT_APP_SERVER_URL=
    environment:
      NODE_ENV: production
      # add additional environment variables
    ports:
      - ${CLIENT_PORT}:80
    depends_on:
      - server
    networks:
      - client-network

  server:
    restart: on-failure:5
    build:
      context: ./server
    ports:
      - ${SERVER_PORT}:8080
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/mern-boilerplate
      CLIENT_URL:
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      SESSION_EXPIRY: ${SESSION_EXPIRY}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
      # add additional environment variables
    depends_on:
      - mongo
    networks:
      - client-network
      - server-network

  mongo:
    image: mongo:latest
    ports:
      - $DB_PORT:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
  client-network:
    driver: bridge

volumes:
  mongo-data:
